### ISSUE TITLE
!todo fess dancetty on per fess

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#165]
!todo fess dancetty on per fess
!draw per fess
i. or, a fess dancetty gules
ii or, a fess indented gules

**Comment by ericscheid** [comment]
the ineffable madness of fess dancetty per fess

![image](https://user-images.githubusercontent.com/2605467/120912979-f8899800-c6d6-11eb-9658-cb5f6ee7d2f1.png)

**Comment by ericscheid** [comment]
Not to worry, a `per pale fess dancetty` couldn't go wrong, right?

![image](https://user-images.githubusercontent.com/2605467/120913062-9b421680-c6d7-11eb-8129-1d3dcf1905b5.png)

Well, at least the `fess indented` worked out right (unlike per fess, where the angles are opposite instead of alternate).
