### ISSUE TITLE
Adjust size of Siberian Cat (?)

### ISSUE THREAD

**Issue by Jackalgirl** [drawshield/Drawshield-Code#228]
The default size of the Siberian Cat results in the critter's back heel being off of the back of the shield for most shield shapes (e.g., heater: https://drawshield.net/create/index.html?blazon=argent%20a%20siberian-cat%20grey&palette=drawshield&shape=heater&effect=none).  I think that if you reduce the size of the SVG to about 80% of what it is now, it might fix the problem (but that's an estimate). 

Note: I wasn't able to adjust the size of the charge myself, but that might just be because I'm not as knowledgeable in the workings of DrawShield and that may make this a non-issue. #220 #

**Comment by karlwilcox** [comment]
This arises because DrawShield doesn't have much understanding of the "shape" of charges - it basically makes a guess (based just on the overall bounding box) and decides that charges are "tall and thin", "short and wide" or "Squarish with round corners" and tries to fill as much of the available space on that basis. Unfortunately the siberian cat has its back foot right in the corner so doesn't fit this sheme very well. For now I've just added some extra space all around it. 
I do have some notes about a scheme to do better shape handling (based on mapping the charge to a 3 x 3 grid) but haven't had time to implement it.
