### ISSUE TITLE
!todo crests are doubled since recent update

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#304]
!todo crests are doubled since recent update
in gallery all crests are doubled, with one in their proper position and second lower and larger

**Comment by ericscheid** [comment]
Possibly related to the fix for this: https://github.com/drawshield/Drawshield-Code/issues/296

[Here is a gallery entry](https://drawshield.net/gallery/61/gallery-6175.html) with proper emblazon, but [recreating with current render](https://drawshield.net/create/index.html?blazon=or%0D%0Atwo%20demi%20antelopes%20gules%20respecting%20each%20other%20in%0A%20chief%20%0D%0Aone%20chevron%20azure%20lower%0D%0Aone%20cross%20fleuronny%20sable%20in%20base%20larger%20higher%0D%0Amantling%20gules%20and%20or%0D%0Aone%20knight%20helmet%20argent%0D%0Atorse%20gules%20and%20or%0D%0Acrest%20on%20one%20portcullis%20or%20one%20%20%20antelope%20gules%20larger%0D%0A%0D%0A) goes wrong.

### buggy render
![buggy render](https://user-images.githubusercontent.com/2605467/144225845-07d7129e-5870-407b-94ea-9286d9e3fac6.png)

### gallery snapshot
![gallery snapshot emblazoning](https://user-images.githubusercontent.com/2605467/144225915-297a38d7-3c56-4198-9004-d171bb99fd4d.png)

**Comment by karlwilcox** [comment]
fixed, now live
