### ISSUE TITLE
Better inescutcheons (hopefully)

### ISSUE THREAD

**Issue by tenshilove** [drawshield/Drawshield-Code#368]
I noticed that currently that there are several issues when inescutcheoning especially regarding charges within the inescutcheoned blazon. First, the charges are not scaled respect to the inescutcheoned blazon, but respect to the base. Secondly, they take the tinctures from the base blazon rather than from the inescutcheon; lastly, the inescutcheoned charges are positioned respect to the base blazon instead of the inescutcheon.

Example:

https://gyazo.com/3848a3e6c3af02f9d291af555986fc2b

Expected result: In the above blazon the dove charge in the example should be scaled to the inescutcheon, countercharged azure and argent and positioned in fess respect to the inescutcheoned blazon.

**Comment by karlwilcox** [comment]
I think this may arise because I made a (possibly artificial) distinction between the inescutcheon, which is a just a charge which happens to be shaped like a heater; and the escutcheon, which is a complete “sub-shield” and (should!) work as you describe, see https://drawshield.net/user-guide/blazon-reference/escutcheons.html but I will look into this.l

**Comment by karlwilcox** [comment]
I'm happy with how this works - an inescutcheon is a charge and works like other charges. An escutcheon is a complete sub-shield that can be placed like a charge. I think this flexibility is useful. I recognise that it breaks some old blazons (in which it is assumed that inescutcheon and escutcheon are the same thing) but I think that the breaking change is worth the extra flexibility
