### ISSUE TITLE
New ducal crown

### ISSUE THREAD

**Issue by PaoloRuben** [drawshield/Drawshield-Code#390]
The HRE (and later Germany), Italy, France and most of the rest of europe used ducal crowns that differ from the english one still they all are composed of 8 acanthus leaves (5 showing) and have an open top, each country differs on specifics, I'd be very glad if anyone of this could be implemented.

A French ducal crown for reference:

![image](https://user-images.githubusercontent.com/57675116/174475765-55107d4b-56c7-4378-902c-6c9461d36c58.png)

**This image is not mine but licensed with license CC BY-SA 3.0**

**Comment by karlwilcox** [comment]
This is done and will be in the next release, you have to say "french ducal crown".

However, I notice that the existing Ducal crown is actually Spanish, so that is now the "spanish ducal crown" and  the English version will be this one https://commons.wikimedia.org/wiki/File:Ducal_crown_(heraldic).svg
