### ISSUE TITLE
!todo `charges in annulo` aren't

### ISSUE THREAD

**Issue by karlwilcox** [drawshield/Drawshield-Code#471]
!todo `charges in annulo` aren't

**Comment by ericscheid** [comment]
`!draw Or, 10 crocodiles in annulo sable`
![image](https://user-images.githubusercontent.com/2605467/200745038-13776e27-1a68-4ad9-841b-bf04194204ac.png)

Logging this issue so the current solution can be found in github.. 

- If you want multiple charges distributed and positioned into a circular path, then the phrasing you want is `n charges arranged in annulo`. You want the charges *arranged*.

- Otherwise the `in annulo` blazon gets parsed as being part of the charge name, in the same way as other *postures* do (.e.g. `a lion rampant`, `a serpent in annulo`, `crow essorant`)

----

That said, the catalogue does have this:
<img width="197" alt="image" src="https://user-images.githubusercontent.com/2605467/200745985-8a67ebfa-a74a-48b7-8d62-03f949c97564.png">

.. which does not match the advice above, and also does not actually work.

So, either the parser needs to be smarter, or the catalogue needs to be fixed.

BTW, the gallery has at least 30 instances of `<n> <charges> in annulo` being rendered as arranged in a circle.

**Comment by ericscheid** [comment]
`!draw Or, 10 crocodiles arranged in annulo sable`
![image](https://user-images.githubusercontent.com/2605467/200747205-ff25c30d-4190-457a-9a91-b53a44db0a8a.png)
